#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x63762CDA67E2F359 (dwmw2@exim.org)
#
Name     : openconnect
Version  : 8.02
Release  : 22
URL      : ftp://ftp.infradead.org/pub/openconnect/openconnect-8.02.tar.gz
Source0  : ftp://ftp.infradead.org/pub/openconnect/openconnect-8.02.tar.gz
Source99 : ftp://ftp.infradead.org/pub/openconnect/openconnect-8.02.tar.gz.asc
Summary  : OpenConnect VPN client
Group    : Development/Tools
License  : LGPL-2.1
Requires: openconnect-bin = %{version}-%{release}
Requires: openconnect-data = %{version}-%{release}
Requires: openconnect-lib = %{version}-%{release}
Requires: openconnect-libexec = %{version}-%{release}
Requires: openconnect-license = %{version}-%{release}
Requires: openconnect-locales = %{version}-%{release}
Requires: openconnect-man = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : krb5-dev
BuildRequires : libgcrypt-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libproxy-1.0)
BuildRequires : pkgconfig(libtasn1)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : pkgconfig(stoken)
BuildRequires : pkgconfig(tss2-esys)
BuildRequires : pkgconfig(zlib)
BuildRequires : python-core
Patch1: 0001-Include-the-vpnc-script-directly-into-the-build.patch

%description
Description:
This directory contains a JNI interface layer for libopenconnect, and a
demo program to show how it can be used.

%package bin
Summary: bin components for the openconnect package.
Group: Binaries
Requires: openconnect-data = %{version}-%{release}
Requires: openconnect-libexec = %{version}-%{release}
Requires: openconnect-license = %{version}-%{release}

%description bin
bin components for the openconnect package.


%package data
Summary: data components for the openconnect package.
Group: Data

%description data
data components for the openconnect package.


%package dev
Summary: dev components for the openconnect package.
Group: Development
Requires: openconnect-lib = %{version}-%{release}
Requires: openconnect-bin = %{version}-%{release}
Requires: openconnect-data = %{version}-%{release}
Provides: openconnect-devel = %{version}-%{release}
Requires: openconnect = %{version}-%{release}

%description dev
dev components for the openconnect package.


%package lib
Summary: lib components for the openconnect package.
Group: Libraries
Requires: openconnect-data = %{version}-%{release}
Requires: openconnect-libexec = %{version}-%{release}
Requires: openconnect-license = %{version}-%{release}

%description lib
lib components for the openconnect package.


%package libexec
Summary: libexec components for the openconnect package.
Group: Default
Requires: openconnect-license = %{version}-%{release}

%description libexec
libexec components for the openconnect package.


%package license
Summary: license components for the openconnect package.
Group: Default

%description license
license components for the openconnect package.


%package locales
Summary: locales components for the openconnect package.
Group: Default

%description locales
locales components for the openconnect package.


%package man
Summary: man components for the openconnect package.
Group: Default

%description man
man components for the openconnect package.


%prep
%setup -q -n openconnect-8.02
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560441390
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static --with-vpnc-script=/usr/share/vpnc/vpnc-script
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1560441390
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openconnect
cp COPYING.LGPL %{buildroot}/usr/share/package-licenses/openconnect/COPYING.LGPL
cp www/licence.xml %{buildroot}/usr/share/package-licenses/openconnect/www_licence.xml
%make_install
%find_lang openconnect

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/openconnect

%files data
%defattr(-,root,root,-)
/usr/share/vpnc/vpnc-script

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libopenconnect.so
/usr/lib64/pkgconfig/openconnect.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopenconnect.so.5
/usr/lib64/libopenconnect.so.5.5.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/openconnect/csd-post.sh
/usr/libexec/openconnect/csd-wrapper.sh
/usr/libexec/openconnect/hipreport.sh
/usr/libexec/openconnect/tncc-wrapper.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openconnect/COPYING.LGPL
/usr/share/package-licenses/openconnect/www_licence.xml

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/openconnect.8

%files locales -f openconnect.lang
%defattr(-,root,root,-)

